### ISSUE TITLE
Improve highlight group links for done state

### ISSUE THREAD

**Issue by akinsho** [kristijanhusak/orgmode.nvim#20]
**Describe the bug**

Currently the done state takes its highlighting from `diffAdd` with some fallbacks around the `Diff` highlight group. I guess this is because these are usually green across most colorschemes. The issue with this is that it isn't dependably a high enough contrast of green. In my case the green is quite muted so that it's easier to make out the added text, but this means that the green as a text highlight rather than background is hard to read.

<img width="396" alt="Screen Shot 2021-06-30 at 10 55 43" src="https://user-images.githubusercontent.com/22454918/123949399-6d7c8480-d99a-11eb-882c-422edeaad08f.png">

**Expected behavior**
A more dependably green highlight might be `String` or tbh if the intent is that the colour should be green then you can alternatively use `guifg={Green|LightGreen}` etc which I believe also works for cterm. That way the colour will be green regardless of the users colorscheme.

I guess this could apply to in progress states as well. It might be that your intention is not to aim for a particular colour at all in which case an alternative or additional solution could be to surface the highlight groups to be overriden. Generally I'm fine with how most colours appear so am not looking to go down a highlight altering rabbit hole, so this is less about surfacing a bunch of highlights and more about a more predictable default.

**Comment by kristijanhusak** [comment]
Yeah, you're right. I wanted to reuse as much colors as possible from the colorscheme with some assumptions that can be wrong sometimes (obviously). I didn't want to use these strict colors because they can be really high in contrast for some colorschemes (Red on dark colorscheme looks really bad for example).

I think there are 2 solutions to this:

1. Introduce a configuration option that would allow defining highlights group that will be used for all of these types
2. Make builtin hl groups from these parsed colors and just `default link` them to the builtin ones. Then user can just do `hi default link OrgTODO Error` or whatever they want to link it to.
3. Implement [orgmode's todo keyword faces](https://orgmode.org/manual/Faces-for-TODO-keywords.html) and just allow users to configure all of these by themselves.

Temporary workaround (which you are probably already aware of) is to override these manually for now:
```vim
hi OrgTODO guifg=Red
hi OrgDONE guifg=Green
hi OrgAgendaDeadline guifg=Red
hi OrgAgendaScheduled guifg=Green
hi OrgAgendaScheduledPast guifg=Orange
```

**Comment by akinsho** [comment]
Thanks for clarifying @kristijanhusak, of the three options the last with the keyword faces seems like something that moves things closer to org's feature set, whereas the other 2 solve just this specific problem so (despite it probably being the most work) it seems like the most likely to tick a few different boxes as well.

Regarding the temporary work around it seems the plugin overrides any attempts by me to change the `OrgDone` highlight. If I apply it explicitly after the agenda or org file is open it works but if I do it before it doesn't. It also doesn't work in a `Colorscheme` autocommand 🤔

**Comment by kristijanhusak** [comment]
Yeah, you're right, i completely forgot it's ran every time. I'll figure something out, thanks.

**Comment by kristijanhusak** [comment]
I pushed a fix. You should be able to override them now. I'm just linking them now so override should work.

**Comment by akinsho** [comment]
@kristijanhusak that helped thanks 👍🏾 , there is still a highlight group for the agenda view that uses the diff colour for the whole line so the word `DONE` takes my highlights but the rest of the line is still a dark colour.

<img width="747" alt="Screen Shot 2021-06-30 at 16 54 49" src="https://user-images.githubusercontent.com/22454918/123992870-e3e1ac80-d9c3-11eb-99f7-e41d6133dec9.png">

**Comment by kristijanhusak** [comment]
@akinsho that should be `hi OrgAgendaScheduled`. What does it return?

**Comment by akinsho** [comment]
That returns
```
:hi OrgAgendaScheduled
OrgAgendaScheduled xxx links to OrgAgendaScheduled_builtin
```

**Comment by kristijanhusak** [comment]
You should be able to override it:
```
hi OrgAgendaScheduled guifg=Green
```

**Comment by akinsho** [comment]
Yep that worked 👍🏾 thanks a bunch 🚀 (again)

**Comment by kristijanhusak** [comment]
@akinsho I added keyword faces support, you can read more about it [here](https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_todo_keyword_faces)

**Comment by Maltimore** [comment]
> Yeah, you're right. I wanted to reuse as much colors as possible from the colorscheme with some assumptions that can be wrong sometimes (obviously). I didn't want to use these strict colors because they can be really high in contrast for some colorschemes (Red on dark colorscheme looks really bad for example).
> 
> I think there are 2 solutions to this:
> 
>     1. Introduce a configuration option that would allow defining highlights group that will be used for all of these types
> 
>     2. Make builtin hl groups from these parsed colors and just `default link` them to the builtin ones. Then user can just do `hi default link OrgTODO Error` or whatever they want to link it to.
> 
>     3. Implement [orgmode's todo keyword faces](https://orgmode.org/manual/Faces-for-TODO-keywords.html) and just allow users to configure all of these by themselves.
> 
> 
> Temporary workaround (which you are probably already aware of) is to override these manually for now:
> 
> ```viml
> hi OrgTODO guifg=Red
> hi OrgDONE guifg=Green
> hi OrgAgendaDeadline guifg=Red
> hi OrgAgendaScheduled guifg=Green
> hi OrgAgendaScheduledPast guifg=Orange
> ```

Hi @kristijanhusak, the highlight groups for TODO and DONE that you mention here still work, even though they are not officially documented. I prefer to use these than to use the new keyword faces colors, because this way I can link other highlight groups. Therefore, when I change my color scheme, the colors will still be reasonable. Should we document that these still exist?

**Comment by kristijanhusak** [comment]
@Maltimore there is some documentation here around colors https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#colors but it's not mentioning todo keyword hl groups. Feel free to add what you think is missing.
