### ISSUE TITLE
would it be possible to use treesitter in this

### ISSUE THREAD

**Issue by crypt17** [kristijanhusak/orgmode.nvim#31]
**Does this feature exist in Emacs orgmode?**
N/A

As treesitter is present in neovim 0.5.0 would it be possible to use that to replace some of the parser code?

**Comment by kristijanhusak** [comment]
Yes, there are some long term plans for that, but I'm not sure when it will happen.

**Comment by akinsho** [comment]
As a future reference, I found: https://github.com/gagbo/tree-sitter-org
a while ago which could be a good starting point but looks incomplete, although I guess things like conceal etc. won't work in the short term.

**Comment by danielnehrig** [comment]
being able to have code blocks with treesitter highlighting would be a must-have feature for me
would love seeing that for reference (https://github.com/vhyrro/neorg) has this implemented

**Comment by kristijanhusak** [comment]
@danielnehrig blocks sre currently highlighted with Vim's syntax highlight. Once there's a treesitter for org, then we can add these. I don't know what's so a "must have" about it, it's just colors.

**Comment by Happy-Dude** [comment]
I'd be interested in seeing a fully-fledged tree-sitter grammer for org-mode as well!

In addition to syntax highlighting, I'm curious if it would help simplify some of the coding/folding/grouping due to it being aware of various [textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects). For me, the highlighting is nice, but the ability to easily select and manipulate blocks and have automatic formatting is a killer-feature.

There was some discussion on organice's Matrix channel (these were the folks who helped make [org-parser](https://github.com/200ok-ch/org-parser)): https://matrix.to/#/!DfVpGxoYxpbfAhuimY:matrix.org/$6BTOYVTBc6mvp9HK95jJRE883ZjFicK_errfIEI-YsQ?via=matrix.org&via=chat.physics.ac&via=nordgedanken.dev

If anything, there is org-parser's [EBNF](https://github.com/200ok-ch/org-parser/blob/master/resources/org.ebnf) for org-mode, and anyone porting the EBNF to a tree-sitter grammar can start there 👍

**Comment by kristijanhusak** [comment]
I'm working on a tree-sitter implementation on a separate branch (feature/ts). There is a tree sitter grammar for org that's fully functional, but I don't want to mention it yet because author (not me) still wants to keep it under the hood. Once I get a green light there I'll publish it for testing.

**Comment by Happy-Dude** [comment]
That is super exciting news, and I wait for the finalized version from you and the team 😃

I'm also curious to hear your thoughts on developing with tree-sitter features/grammars compared to regular syntax parsers afterwards!

**Comment by kristijanhusak** [comment]
Tree-sitter support is added on branch https://github.com/kristijanhusak/orgmode.nvim/tree/tree-sitter. I would appreciate if everyone would switch to it so we can start testing this out.

**Comment by Happy-Dude** [comment]
Thanks, excited to play around with this over the course of the next week!

Would it be correct that orgmode.nvim is using https://github.com/milisims/tree-sitter-org and to install that manually for now?

**Comment by kristijanhusak** [comment]
Yes, you need to install it manually for now. Readme has everything that you need.

**Comment by kristijanhusak** [comment]
Tree-sitter branch is now officially merged to master https://github.com/kristijanhusak/orgmode.nvim/pull/139. 
Thanks to all the help from the people who tested the pre-release.
